### ISSUE TITLE
DBS moolahtycoon PAGE HANG....

### ISSUE THREAD

**Issue by fusenet** [fusenet/Defu-five-e#1]
![Screenshot_20220912-230457_Chrome.jpg](https://user-images.githubusercontent.com/106623352/189986186-2140d203-8ea3-4cba-97a7-6b8be1f4c204.jpg)

**Comment by FuseAkhi** [comment]
{Screenshot_20220912-230457_Chrome.jpg](https://user-images.githubusercontent.com/106623352/189986186-2140d203-8ea3-4cba-97a7-6b8be1f4c204.jpg)

**Comment by FuseAkhi** [comment]
> ![Screenshot_20220912-230457_Chrome.jpg](https://user-images.githubusercontent.com/106623352/189986186-2140d203-8ea3-4cba-97a7-6b8be1f4c204.jpg)

Solutions anyone?
